### ISSUE TITLE
confusion about how to inference the task_id in class_incremental learning

### ISSUE THREAD

**Issue by Logictaosen007** [CVIR/contracon#1]
if model_args.scenario == 'cil' and tot_task>0:
                    correct_sample,Ncorrect,_=check_task(task, inputs, targets, model,task_parent_dict, tot_task)
                    tcorrect+=Ncorrect
                    inputs1=inputs1[correct_sample]
                    targets=targets[correct_sample]
Sir,is the code above corresponding to the inferences of task_id? I try to use this method in cil. But AVERAGE TASK CORRECT = 0.232, this may case the  reduction in the number of images in the test set.

**Comment by ranarag** [comment]
The check_task function finds the correct task_id for the inputs and the inputs1 variable selects only those inputs whose task_id have been predicted correctly.
